model: omgsr_s_256
seed: 523
sd_path: stabilityai/stable-diffusion-2-1-base
fixed_prompt: ""   # empty prompt is ok!
fixed_prompt_path: null
dataset_txt_or_dir_paths: ["dataset/train_rgb/ER/HQ", "dataset/train_rgb/ER/LQ"]

vae_lora_rank: 16
unet_lora_rank: 32

dinov3_convnext_size: large      # tiny, small, base, large
lambda_LRR: 5
lambda_Dv3D: 0.5 #reduce natural image constrain
lambda_L1: 5.0
lambda_GAN: 0.05
lambda_SSIM: 2.0
mid_timestep: 276 # modify mid_timestep from 273 to 254(CCPs) //ER 276

output_dir: ./omgsr_trainings/ER_with_edge_aware_mask
resolution: 256
train_batch_size: 4 # later add up to 4 or 8, may stablize GAN training
max_train_steps: 50000
checkpointing_steps: 1000
save_img_steps: 100
resume_from_checkpoint: null
gradient_accumulation_steps: 1 #later cut down to 1, the same as train_batch_size
gradient_checkpointing: False
enable_xformers_memory_efficient_attention: False
learning_rate: 5e-5
lr_scheduler: cosine
lr_warmup_steps: 500
lr_num_cycles: 1
lr_power: 1.0
dataloader_num_workers: 8
use_8bit_adam: False
adam_beta1: 0.9
adam_beta2: 0.999
adam_weight_decay: 1e-4
adam_epsilon: 1e-08
max_grad_norm: 1.0
logging_dir: logs
allow_tf32: False
mixed_precision: bf16


